"""Excel upload — bulk candidate insert with domain auto-assignment."""
import io
import json
import re
import xml.etree.ElementTree as ET

import openpyxl
from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import StreamingResponse
from typing import Optional

from services.auth_service import require_admin_or_superadmin
from services.supabase_client import get_service_client
from services.excel_parser import parse_excel

router = APIRouter()

ALLOWED_EXTENSIONS = {".xlsx", ".xls"}


def _ndjson(payload: dict) -> str:
    return json.dumps(payload, ensure_ascii=False) + "\n"


def _normalize_domain(value: str) -> str:
    return re.sub(r"[^a-z0-9]", "", str(value).strip().lower())


def _resolve_domain_id(
    excel_name: str,
    exact_name_map: dict[str, str],
    normalized_map: dict[str, str],
) -> Optional[str]:
    # First try exact lower-cased match.
    key = excel_name.strip().lower()
    if key in exact_name_map:
        return exact_name_map[key]

    # Then try normalized match (ignores spaces/punctuation/case).
    norm = _normalize_domain(excel_name)
    if not norm:
        return None
    if norm in normalized_map:
        return normalized_map[norm]

    # Finally, handle short fragments such as "web" -> "Web Development".
    for dom_norm, dom_id in normalized_map.items():
        if norm in dom_norm or dom_norm in norm:
            return dom_id

    return None


def _parse_spreadsheetml_workbook(contents: bytes):
    """Parse the XML Spreadsheet format generated by the offline backup export."""
    ns = {
        "ss": "urn:schemas-microsoft-com:office:spreadsheet",
        "x": "urn:schemas-microsoft-com:office:excel",
    }
    root = ET.fromstring(contents.decode("utf-8-sig"))
    workbook = {"sheetnames": [], "sheets": {}}

    for worksheet in root.findall(".//{urn:schemas-microsoft-com:office:spreadsheet}Worksheet"):
        sheet_name = worksheet.attrib.get("{urn:schemas-microsoft-com:office:spreadsheet}Name") or worksheet.attrib.get("ss:Name")
        if not sheet_name:
          continue
        workbook["sheetnames"].append(sheet_name)
        rows = []
        table = worksheet.find("{urn:schemas-microsoft-com:office:spreadsheet}Table")
        if table is None:
            workbook["sheets"][sheet_name] = rows
            continue
        for row in table.findall("{urn:schemas-microsoft-com:office:spreadsheet}Row"):
            cells = []
            for cell in row.findall("{urn:schemas-microsoft-com:office:spreadsheet}Cell"):
                data = cell.find("{urn:schemas-microsoft-com:office:spreadsheet}Data")
                cells.append(data.text if data is not None and data.text is not None else None)
            rows.append(cells)
        workbook["sheets"][sheet_name] = rows

    return workbook


def _load_recovery_workbook(contents: bytes):
    try:
        return {"kind": "openpyxl", "workbook": openpyxl.load_workbook(io.BytesIO(contents), data_only=True)}
    except Exception:
        try:
            return {"kind": "spreadsheetml", "workbook": _parse_spreadsheetml_workbook(contents)}
        except Exception as e:
            raise HTTPException(status_code=422, detail=f"Failed to parse Excel: {e}")


@router.post("/excel")
async def upload_excel(
    file: UploadFile = File(...),
    domain_ids: Optional[str] = Form(None),   # comma-separated UUIDs chosen in the UI
    user=Depends(require_admin_or_superadmin),
):
    ext = "." + file.filename.rsplit(".", 1)[-1].lower()
    if ext not in ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=400, detail="Only .xlsx/.xls files accepted")

    contents = await file.read()
    if len(contents) > 10 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="File too large (max 10MB)")

    try:
        records = parse_excel(contents)
    except Exception as e:
        raise HTTPException(status_code=422, detail=f"Failed to parse Excel: {e}")

    if not records:
        raise HTTPException(status_code=400, detail="No valid candidate rows found")

    svc = get_service_client()

    # Build domain map for names found inside the Excel (existing behaviour)
    domain_res = svc.table("domains").select("id, name").execute()
    domain_name_map = {d["name"].strip().lower(): d["id"] for d in (domain_res.data or [])}
    domain_norm_map = {_normalize_domain(d["name"]): d["id"] for d in (domain_res.data or [])}

    # Parse the explicitly chosen domain_ids from the UI
    chosen_domain_ids: list[str] = []
    if domain_ids:
        chosen_domain_ids = [d.strip() for d in domain_ids.split(",") if d.strip()]

    def event_stream():
        inserted = 0
        skipped = 0
        errors = []
        total_rows = len(records)

        yield _ndjson({"type": "meta", "phase": "processing", "sheet": "Participants", "total": total_rows})

        for index, rec in enumerate(records, start=1):
            excel_domain_names = rec.pop("domains", [])   # names from the Excel column
            candidate_payload = {k: v for k, v in rec.items() if v not in (None, "")}
            candidate_payload["created_by"] = user["id"]
            display_name = candidate_payload.get("name") or candidate_payload.get("full_name") or candidate_payload.get("email") or f"Row {index}"

            try:
                c_res = svc.table("candidates").upsert(
                    candidate_payload, on_conflict="email"
                ).execute()

                if not c_res.data:
                    skipped += 1
                    errors.append({"email": rec.get("email"), "error": "No row returned from upsert"})
                    yield _ndjson({
                        "type": "row",
                        "phase": "processing",
                        "sheet": "Participants",
                        "index": index,
                        "total": total_rows,
                        "status": "skipped",
                        "name": display_name,
                        "email": rec.get("email"),
                        "message": "Skipped",
                    })
                    continue

                candidate_id = c_res.data[0]["id"]

                all_domain_ids: set[str] = set(chosen_domain_ids)
                for name in excel_domain_names:
                    did = _resolve_domain_id(name, domain_name_map, domain_norm_map)
                    if did:
                        all_domain_ids.add(did)

                if all_domain_ids:
                    domain_records = [
                        {
                            "candidate_id": candidate_id,
                            "domain_id": did,
                            "assigned_by": user["id"],
                        }
                        for did in all_domain_ids
                    ]
                    svc.table("candidate_domains").upsert(
                        domain_records, on_conflict="candidate_id,domain_id"
                    ).execute()

                inserted += 1
                yield _ndjson({
                    "type": "row",
                    "phase": "processing",
                    "sheet": "Participants",
                    "index": index,
                    "total": total_rows,
                    "status": "inserted",
                    "name": display_name,
                    "email": rec.get("email"),
                    "candidate_id": candidate_id,
                    "message": f"Uploaded {display_name}",
                })

            except Exception as e:
                skipped += 1
                errors.append({"email": rec.get("email"), "error": str(e)})
                yield _ndjson({
                    "type": "row",
                    "phase": "processing",
                    "sheet": "Participants",
                    "index": index,
                    "total": total_rows,
                    "status": "error",
                    "name": display_name,
                    "email": rec.get("email"),
                    "message": str(e),
                })

        yield _ndjson({
            "type": "done",
            "result": {
                "total_rows": total_rows,
                "inserted": inserted,
                "skipped": skipped,
                "errors": errors[:20],
            },
        })

    return StreamingResponse(event_stream(), media_type="application/x-ndjson")


@router.post("/recovery/import")
async def import_recovery_excel(
    file: UploadFile = File(...),
    _=Depends(require_admin_or_superadmin),
):
    ext = "." + file.filename.rsplit(".", 1)[-1].lower()
    if ext not in ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=400, detail="Only .xlsx/.xls files accepted")

    contents = await file.read()
    if len(contents) > 15 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="File too large (max 15MB)")

    parsed = _load_recovery_workbook(contents)

    svc = get_service_client()
    processed = 0
    success = 0
    failed = 0
    errors = []

    def _header_map(ws):
        headers = [str(c.value or "").strip().lower() for c in ws[1]]
        return {h: i for i, h in enumerate(headers) if h}

    def _row_to_dict(row, hmap):
        out = {}
        for h, idx in hmap.items():
            out[h] = row[idx].value if idx < len(row) else None
        return out

    def _to_json_or_empty(value):
        if not value:
            return {}
        if isinstance(value, dict):
            return value
        try:
            return json.loads(str(value))
        except Exception:
            return {}

    def recovery_stream():
        stats = {"processed": 0, "successful": 0, "failed": 0, "errors": []}

        def handle_participant(rec, index, total_rows):
            display_name = str(rec.get("name") or rec.get("full_name") or rec.get("email") or f"Row {index}")
            if not rec.get("id") or not rec.get("email") or not rec.get("name"):
                yield _ndjson({"type": "row", "sheet": "Participants", "phase": "processing", "index": index, "total": total_rows, "status": "skipped", "name": display_name, "email": rec.get("email"), "message": "Missing required fields"})
                return
            try:
                payload = {
                    "id": str(rec.get("id")),
                    "name": str(rec.get("name")),
                    "email": str(rec.get("email")).lower(),
                    "phone": rec.get("phone"),
                    "roll_number": rec.get("roll_number"),
                    "branch": rec.get("branch"),
                    "section": rec.get("section"),
                    "year": rec.get("year"),
                    "skills": rec.get("skills"),
                    "experience": rec.get("experience"),
                    "status": rec.get("status") or "pending",
                    "extra_data": _to_json_or_empty(rec.get("extra_data")),
                }
                svc.table("candidates").upsert(payload, on_conflict="id").execute()
                raw_domains = str(rec.get("candidate_domains") or "").strip()
                if raw_domains:
                    domain_ids = [d.strip() for d in raw_domains.split(",") if d.strip()]
                    svc.table("candidate_domains").delete().eq("candidate_id", str(rec.get("id"))).execute()
                    rows = [{"candidate_id": str(rec.get("id")), "domain_id": did} for did in domain_ids]
                    if rows:
                        svc.table("candidate_domains").upsert(rows, on_conflict="candidate_id,domain_id").execute()
                stats["processed"] += 1
                stats["successful"] += 1
                yield _ndjson({"type": "row", "sheet": "Participants", "phase": "processing", "index": index, "total": total_rows, "status": "inserted", "name": display_name, "email": rec.get("email"), "message": f"Uploaded {display_name}"})
            except Exception as e:
                stats["processed"] += 1
                stats["failed"] += 1
                stats["errors"].append({"sheet": "Participants", "error": str(e)})
                yield _ndjson({"type": "row", "sheet": "Participants", "phase": "processing", "index": index, "total": total_rows, "status": "error", "name": display_name, "email": rec.get("email"), "message": str(e)})

        def handle_evaluation(rec, index, total_rows):
            display_name = str(rec.get("candidate_id") or rec.get("id") or f"Row {index}")
            if not rec.get("candidate_id") or not rec.get("domain_id") or not rec.get("admin_id"):
                yield _ndjson({"type": "row", "sheet": "Evaluations", "phase": "processing", "index": index, "total": total_rows, "status": "skipped", "name": display_name, "message": "Missing required fields"})
                return
            try:
                payload = {
                    "id": str(rec.get("id")) if rec.get("id") else None,
                    "candidate_id": str(rec.get("candidate_id")),
                    "domain_id": str(rec.get("domain_id")),
                    "admin_id": str(rec.get("admin_id")),
                    "round_number": int(rec.get("round_number") or 1),
                    "scores": _to_json_or_empty(rec.get("scores")),
                    "total_score": float(rec.get("total_score") or 0),
                    "remarks": rec.get("remarks"),
                }
                svc.table("evaluations").upsert(payload, on_conflict="candidate_id,domain_id,admin_id").execute()
                stats["processed"] += 1
                stats["successful"] += 1
                yield _ndjson({"type": "row", "sheet": "Evaluations", "phase": "processing", "index": index, "total": total_rows, "status": "inserted", "name": display_name, "message": "Uploaded evaluation"})
            except Exception as e:
                stats["processed"] += 1
                stats["failed"] += 1
                stats["errors"].append({"sheet": "Evaluations", "error": str(e)})
                yield _ndjson({"type": "row", "sheet": "Evaluations", "phase": "processing", "index": index, "total": total_rows, "status": "error", "name": display_name, "message": str(e)})

        def stream_openpyxl():
            wb = parsed["workbook"]
            if "Participants" in wb.sheetnames:
                ws = wb["Participants"]
                total_rows = max(ws.max_row - 1, 0)
                yield _ndjson({"type": "meta", "sheet": "Participants", "phase": "processing", "total": total_rows})
                hmap = _header_map(ws)
                for index, row in enumerate(ws.iter_rows(min_row=2), start=1):
                    rec = _row_to_dict(row, hmap)
                    yield from handle_participant(rec, index, total_rows)

            if "Evaluations" in wb.sheetnames:
                ws = wb["Evaluations"]
                total_rows = max(ws.max_row - 1, 0)
                yield _ndjson({"type": "meta", "sheet": "Evaluations", "phase": "processing", "total": total_rows})
                hmap = _header_map(ws)
                for index, row in enumerate(ws.iter_rows(min_row=2), start=1):
                    rec = _row_to_dict(row, hmap)
                    yield from handle_evaluation(rec, index, total_rows)

        def stream_spreadsheetml():
            wb = parsed["workbook"]
            participant_rows = wb["sheets"].get("Participants", [])
            if participant_rows:
                headers = [str(v or "").strip().lower() for v in participant_rows[0]]
                total_rows = max(len(participant_rows) - 1, 0)
                yield _ndjson({"type": "meta", "sheet": "Participants", "phase": "processing", "total": total_rows})
                for index, values in enumerate(participant_rows[1:], start=1):
                    rec = {headers[i]: values[i] if i < len(values) else None for i in range(len(headers))}
                    yield from handle_participant(rec, index, total_rows)

            evaluation_rows = wb["sheets"].get("Evaluations", [])
            if evaluation_rows:
                headers = [str(v or "").strip().lower() for v in evaluation_rows[0]]
                total_rows = max(len(evaluation_rows) - 1, 0)
                yield _ndjson({"type": "meta", "sheet": "Evaluations", "phase": "processing", "total": total_rows})
                for index, values in enumerate(evaluation_rows[1:], start=1):
                    rec = {headers[i]: values[i] if i < len(values) else None for i in range(len(headers))}
                    yield from handle_evaluation(rec, index, total_rows)

        if parsed["kind"] == "openpyxl":
            yield from stream_openpyxl()
        else:
            yield from stream_spreadsheetml()

        yield _ndjson({"type": "done", "result": {"processed": stats["processed"], "successful": stats["successful"], "failed": stats["failed"], "errors": stats["errors"][:50]}})

    return StreamingResponse(recovery_stream(), media_type="application/x-ndjson")
